spring.application.name=code-gen-mybatis

spring.datasource.url=jdbc:mysql://localhost:3306/test
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#要施作的專案
codegen.paths.vo=/Users/rinchan/Desktop/Lynn/oauth_demo/src/main/java/com/lynn/oauth_demo/vo
codegen.paths.dao=/Users/rinchan/Desktop/Lynn/oauth_demo/src/main/java/com/lynn/oauth_demo/dao
codegen.paths.mapper=/Users/rinchan/Desktop/Lynn/oauth_demo/src/main/resources/mybatis
basePackage=com.lynn.oauth_demo
